name: File processing test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/file-processing.yml"
      - "file-processing/"

jobs:
  test-it:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test it
        working-directory: file-processing
        run: |
          echo "---- Before"
          cat wrangler.toml

          cat wrangler.toml | sed 's/main = "build/main = "result/' | sed 's/command = "worker-build --release"/command = "echo dummy build"/' >| wrangler.toml

          echo "---- After"
          cat wrangler.toml
